version: '3.8'

services:
  app:
    build: .
    container_name: news-backend
    ports:
      - "4009:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NEXT_PUBLIC_SUPABASE_URL : ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY : ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      PORT : ${PORT}
      NEXT_PUBLIC_NEWS_API_KEY : ${NEXT_PUBLIC_NEWS_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]
