version: "3.9"

services:
  news-backend:
    container_name: news-backend
    image: nolandev1/news-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4000:4000"
    labels:
      - "traefik.http.routers.news-backend.rule=(Host(`newsbackend.navong.xyz`) && PathPrefix(`/api`))"
    networks:
      - traefik-network
    restart: unless-stopped

networks:
  traefik-network:
    external: true









