version: "3.9"

services:
  news-backend:
    container_name: news-backend
    image: nolandev1/news-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "4000:4000"
    labels:
      - "traefik.http.routers.news-backend.rule=(Host(`newsbackend.navong.xyz`) && PathPrefix(`/api`))"
      - "traefik.http.routers.news-backend.rule=(Host(`newsbackend.navong.xyz`) && PathPrefix(`/`))"
    networks:
      - traefik-network
    restart: unless-stopped

  db-seeder:
    image: node:18
    container_name: db-seeder
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["sh", "-c", "apt-get update && apt-get install -y cron && cron -f"]
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: >
      bash -c "echo '0 8 * * * cd /app && npx prisma db seed' >> /etc/crontab &&
               echo '0 14 * * * cd /app && npx prisma db seed' >> /etc/crontab &&
               echo '0 20 * * * cd /app && npx prisma db seed' >> /etc/crontab &&
               cron -f"
    networks:
      - traefik-network
    restart: unless-stopped
    
networks:
  traefik-network:
    external: true

